### ISSUE TITLE
Error in pandas_matriz_zone_translation

### ISSUE THREAD

**Issue by isaac-tfn** [Transport-for-the-North/caf.toolkit#77]
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

Error raised when running a zone translation. This is after it falls back to the low memory version.

**Comment by isaac-tfn** [comment]
> Are you able to recreate the error? Do you have an MVP that causes the error to happen?

This error was my fault but when fixed I got another one. I'm now just using my multicolumn vector translation twice and it seems to be faster and more memory efficient.

**Comment by isaac-tfn** [comment]
`lookup = pd.read_csv(r"I:\Data\Zone Translations\cache\noham_ntem\noham_to_ntem_pop_2018.csv")
mat = pd.read_csv("E:\ntem_outputs\Forecasting\NTEM\8.0\iter3.2\Core\car_and_passenger\Matrices\OD\hb_od_from_yr2025_p1_m3_Core_tp1.csv.bz2", index_col=0)
trans = translation.pandas_matrix_zone_translation(matrix=mat,
                                                              translation=lookup,
                                                              translation_from_col='noham_id',
                                                              translation_to_col='ntem_id',
                                                              translation_factors_col='noham_to_ntem',
                                                              from_unique_index=lookup['noham_id'].unique(),
                                                              to_unique_index=lookup['ntem_id'].unique()
                                                              )`

This code raises the error - I have code runnin right now so I can't replicate it but it was raised when running in debug if that affects it.

The alternative is the same code, except instead of zone translation it's

`translation.pandas_vector_zone_translation().transpose()`

twice, with the arguments the same (replace kwd matrix with vector). You also need to set check_totals to false as the translation drops Scotland, which is fine.

**Comment by BenTaylor-TfN** [comment]
I'm pretty sure this is an issue with running in debug mode in PyCharm.

I think it's something to do with the debug mode needing to use a lot more memory and needing to keep track of a lot more stuff. In some cases, this just results in the system looking like it's doing nothing.

It's probably clear, but it's worth pointing out that `pandas_multi_vector_zone_translation()` is doing the same thing as half of the `pandas_matrix_zone_translation()` when it falls back to the slow method. **This should be consolidated**.

## Run results
I've just ran this code and it worked fine, and about how I expected.
- The matrix zone translation took ~2/3 mins as expected, using about 10Gb of memory in total.
- The vector method took ~2/3 seconds, again using about 10Gb of memory in total.

It's worth noting a few things:
- The pandas matrix zone translation falls back to a slow method if it runs out of memory - that's happening here
- The slow method does scale with more cores
- That said, this is a particularly bad example for pandas matrix translation. The data is just too big to instantly translate.

Finally, I've known this is an issue for a while and never got round to optimising the "slow" translation. I think this is the route we should now take.

## Further tests
I think there's a few things we should investigate further here:
- How does this exact same test perform when run on a system with more memory and cores?
- How does this test run when we use bigger zoning systems in the translation, such as MSOA to NoHAM? 

Furthermore, it's clear the "slow" method needs optimising. I see two options:
1. Just replace it with the multi-vector function. Although, this is written in pandas so it will need updating for numpy data.
2. Investigate numba / cython optimisations for the current code. It's slow because it's a `for` loop.

The two options should all be tested with the above tests as well to make sure we end up with the optimal version of code.
